// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using todo_api.Models;

namespace todo_api.Migrations
{
    [DbContext(typeof(TodoApiContext))]
    partial class TodoApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("todo_api.Models.CheckList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CheckListData");

                    b.Property<int?>("NoteID");

                    b.Property<bool>("Status");

                    b.HasKey("ID");

                    b.HasIndex("NoteID");

                    b.ToTable("CheckList");
                });

            modelBuilder.Entity("todo_api.Models.Label", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LabelData");

                    b.Property<int?>("NoteID");

                    b.HasKey("ID");

                    b.HasIndex("NoteID");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("todo_api.Models.Note", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Pinned");

                    b.Property<string>("PlainText");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("todo_api.Models.CheckList", b =>
                {
                    b.HasOne("todo_api.Models.Note")
                        .WithMany("CheckLists")
                        .HasForeignKey("NoteID");
                });

            modelBuilder.Entity("todo_api.Models.Label", b =>
                {
                    b.HasOne("todo_api.Models.Note")
                        .WithMany("Labels")
                        .HasForeignKey("NoteID");
                });
#pragma warning restore 612, 618
        }
    }
}
